[project]
name = "pmll"
description = "PMLL smart contract suite for DrQSatoshin.com"
authors = ["Josef Kurk Edwards"]
telemetry = true
cache_dir = "./.cache"

[contracts.pmll-traits]
path = "contracts/traits/pmll-traits.clar"
epoch = "latest"

[contracts.pmll-vault]
path = "contracts/pmll-vault.clar"
epoch = "latest"
depends_on = ["pmll-traits"]

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
