[network]
name = "devnet"
node_rpc_address = "http://localhost:20443"
deployment_fee_rate = 10

# =========================
# Accounts (pre-funded)
# =========================
[[accounts]]
name = "deployer"
address = "ST70NNDG2PF1CA1T651VSEDRZ0PJNJ24GEC1ZZG5"
balance = 100000000000000

[[accounts]]
name = "wallet_1"
balance = 100000000000000

[[accounts]]
name = "wallet_2"
balance = 100000000000000

# =========================
# Contracts to deploy
# =========================
[[contracts]]
name = "pmll-traits"
deployer = "deployer"

[[contracts]]
name = "pmll-vault"
deployer = "deployer"

# =========================
# Devnet Behavior
# =========================
[devnet]
miner = "deployer"
block_time = 10
